export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_RELOAD = "LOGIN_RELOAD";
export const LOGIN_SUCCEED = "LOGIN_SUCCEED";

export const GET_SERVER_FAIL = "GET_SERVER_FAIL";
export const GET_SERVER_LOADING = "GET_SERVER_LOADING";
export const GET_SERVER_RELOAD = "GET_SERVER_RELOAD";
export const GET_SERVER_SUCCEED = "GET_SERVER_SUCCEED";

export const SOCKET_FAIL = "SOCKET_FAIL";
export const SOCKET_LOADING = "SOCKET_LOADING";
export const SOCKET_RELOAD = "SOCKET_RELOAD";
export const SOCKET_SUCCEED = "SOCKET_SUCCEED";